

1120/1120 [==============================] - ETA: 0s - loss: 3.1617 - accuracy: 0.6468 - top-5-accuracy: 0.86472023-05-19 19:34:34.715187: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [5293]
         [[{{node Placeholder/_4}}]]
2023-05-19 19:34:34.715405: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [5293]
         [[{{node Placeholder/_4}}]]
1120/1120 [==============================] - 785s 673ms/step - loss: 3.1617 - accuracy: 0.6468 - top-5-accuracy: 0.8647 - val_loss: 6.1009 - val_accuracy: 0.1116 - val_top-5-accuracy: 0.2150 - lr: 0.0010
Epoch 2/10
1120/1120 [==============================] - 761s 680ms/step - loss: 2.7854 - accuracy: 0.7594 - top-5-accuracy: 0.9411 - val_loss: 6.1618 - val_accuracy: 0.1174 - val_top-5-accuracy: 0.2195 - lr: 0.0010
Epoch 3/10
1120/1120 [==============================] - 749s 669ms/step - loss: 2.5866 - accuracy: 0.8271 - top-5-accuracy: 0.9753 - val_loss: 6.1775 - val_accuracy: 0.1176 - val_top-5-accuracy: 0.2174 - lr: 0.0010
Epoch 4/10
1120/1120 [==============================] - 754s 674ms/step - loss: 2.4435 - accuracy: 0.8778 - top-5-accuracy: 0.9883 - val_loss: 6.1938 - val_accuracy: 0.1231 - val_top-5-accuracy: 0.2180 - lr: 0.0010
Epoch 5/10
1120/1120 [==============================] - 748s 668ms/step - loss: 2.3602 - accuracy: 0.9006 - top-5-accuracy: 0.9929 - val_loss: 6.1895 - val_accuracy: 0.1218 - val_top-5-accuracy: 0.2165 - lr: 2.0000e-04
Epoch 6/10
 584/1120 [==============>...............] - ETA: 5:41 - loss: 2.3215 - accuracy: 0.9102 - top-5-accuracy: 0.9933 
 